name: WordPress Health Check

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2 AM UTC

jobs:
  wordpress-health-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies and Playwright browsers
      run: |
        echo "Installing dependencies..."
        npm ci
        echo "Installing Playwright browsers..."
        npx playwright install --with-deps

    - name: Run WordPress Health Check
      run: |
        echo "Running WordPress health checks..."
        npx playwright test tests/essential-tests.spec.js
      env:
        WP_BASE_URL: ${{ secrets.WP_BASE_URL || 'https://beratta.websearchpro.net' }}
        WP_ADMIN_USER: ${{ secrets.WP_ADMIN_USER || 'admin' }}
        WP_ADMIN_PASS: ${{ secrets.WP_ADMIN_PASS || 'taJdMiIvQdht4XGO%!ycgk6Z' }}
        
    - name: Upload Simple Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: simple-health-report
        path: simple-test-report.html
        retention-days: 30
        
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/**
        retention-days: 30
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/**
        retention-days: 30
